# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Import-Export.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 600)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_find_path = QtWidgets.QTextEdit(self.centralwidget)
        self.text_find_path.setGeometry(QtCore.QRect(10, 40, 141, 21))
        self.text_find_path.setObjectName("text_find_path")
        self.text_find_ext = QtWidgets.QTextEdit(self.centralwidget)
        self.text_find_ext.setGeometry(QtCore.QRect(160, 40, 61, 21))
        self.text_find_ext.setObjectName("text_find_ext")
        self.btn_find = QtWidgets.QPushButton(self.centralwidget)
        self.btn_find.setGeometry(QtCore.QRect(370, 40, 101, 21))
        self.btn_find.setObjectName("btn_find")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(480, 0, 291, 371))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.text_import_excel = QtWidgets.QTextEdit(self.centralwidget)
        self.text_import_excel.setGeometry(QtCore.QRect(10, 90, 321, 21))
        self.text_import_excel.setObjectName("text_import_excel")
        self.text_export_excel = QtWidgets.QTextEdit(self.centralwidget)
        self.text_export_excel.setGeometry(QtCore.QRect(10, 140, 311, 21))
        self.text_export_excel.setObjectName("text_export_excel")
        self.btn_import_excel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_import_excel.setGeometry(QtCore.QRect(340, 90, 111, 21))
        self.btn_import_excel.setObjectName("btn_import_excel")
        self.btn_export_excel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_export_excel.setGeometry(QtCore.QRect(330, 140, 121, 21))
        self.btn_export_excel.setObjectName("btn_export_excel")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(10, 450, 691, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(14)
        self.label_error.setFont(font)
        self.label_error.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.text_find_time = QtWidgets.QTextEdit(self.centralwidget)
        self.text_find_time.setGeometry(QtCore.QRect(230, 40, 131, 21))
        self.text_find_time.setObjectName("text_find_time")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 10, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 47, 13))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_find.setText(_translate("MainWindow", "Filter"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "FileName"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Path"))
        self.btn_import_excel.setText(_translate("MainWindow", "Import from excel"))
        self.btn_export_excel.setText(_translate("MainWindow", "Export to Excel"))
        self.label.setText(_translate("MainWindow", "Path"))
        self.label_2.setText(_translate("MainWindow", "Ext"))
        self.label_3.setText(_translate("MainWindow", "Time Modified"))
        self.label_4.setText(_translate("MainWindow", "File Name"))
        self.label_5.setText(_translate("MainWindow", "File Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
